version: '3.3' 

volumes: 
  static:
  backend_static:
  backend_media:
  pg_data:

services:
  db:
    container_name: postgre_db_prod
    image: postgres:latest 
    env_file: .env 
    volumes: 
      - pg_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
   
  backend: 
    image: alvel007/opjournals_backend:latest 
    env_file: .env 
    depends_on: 
      - db 
    volumes: 
      - backend_static:/app/static
      - backend_media:/app/media

  nginx: 
    image: nginx:latest 
    env_file: .env 
    ports: 
      - "8080:80" 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/ks