# Generated by Django 4.2.7 on 2023-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='administrative_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='operational_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='administrative_staff',
            field=models.ManyToManyField(blank=True, default=None, related_name='administrative_staff', to='substation.substation', verbose_name='АТП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='operational_staff',
            field=models.ManyToManyField(blank=True, related_name='operational_staff', to='substation.substation', verbose_name='ОП'),
        ),
    ]
