# Generated by Django 4.2.7 on 2023-11-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_customuser_administrative_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
