# Generated by Django 4.2.7 on 2023-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_customuser_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке персонала'),
        ),
    ]
