# Generated by Django 4.2.7 on 2023-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0003_alter_substation_slug'),
        ('staff', '0007_alter_customuser_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='administrative_staff',
            field=models.ManyToManyField(blank=True, default=None, related_name='administrative_staff', to='substation.substation', verbose_name='Административно-технические права'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='operational_staff',
            field=models.ManyToManyField(blank=True, related_name='operational_staff', to='substation.substation', verbose_name='Оперативные права'),
        ),
    ]
