# Generated by Django 4.2.7 on 2023-11-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_customuser_administrative_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Электромонтер по обслуживанию', 'Электромонтер по обслуживанию'), ('Дежурный инженер', 'Дежурный инженер'), ('Дежурный инженер 2 кат.', 'Дежурный инженер 2 кат.'), ('Дежурный инженер 1 кат.', 'Дежурный инженер 1 кат.'), ('Диспетчер ЦУС', 'Диспетчер ЦУС'), ('Ведущий инженер гр. ПС', 'Ведущий инженер гр. ПС'), ('Ведущий инженер по ОП гр. ПС', 'Ведущий инженер по ОП гр. ПС'), ('Начальник ПС', 'Начальник ПС'), ('Начальник гр. ПС', 'Начальник гр. ПС'), ('Начальник ООР', 'Начальник ООР'), ('Начальник ЦУС', 'Начальник ЦУС'), ('АТП ПМЭС', 'АТП ПМЭС')], default='', max_length=120, null=True, verbose_name='Должность'),
        ),
    ]
