# Generated by Django 4.2.7 on 2023-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_customuser_admin_opj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Электромонтер по обслуживанию', 'Электромонтер по обслуживанию'), ('Дежурный инженер', 'Дежурный инженер'), ('Дежурный инженер 2 кат.', 'Дежурный инженер 2 кат.'), ('Дежурный инженер 1 кат.', 'Дежурный инженер 1 кат.'), ('Диспетчер ЦУС', 'Диспетчер ЦУС'), ('Ведущий инженер', 'Ведущий инженер'), ('Ведущий инженер по ОП', 'Ведущий инженер по ОП'), ('Начальник', 'Начальник'), ('Начальник ООР', 'Начальник ООР'), ('Начальник ЦУС', 'Начальник ЦУС'), ('АТП ПМЭС', 'АТП ПМЭС')], default='', max_length=120, null=True, verbose_name='Должность'),
        ),
    ]
