# Generated by Django 4.2.7 on 2023-12-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_groupsubstation_group_boss_and_more'),
        ('staff', '0012_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_place_work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.substation', verbose_name='Основное место работы'),
        ),
    ]
