# Generated by Django 4.2.7 on 2023-12-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_groupsubstation_group_boss_and_more'),
        ('staff', '0013_customuser_main_place_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_place_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.substation', verbose_name='Основное место работы'),
        ),
    ]
