# Generated by Django 4.2.7 on 2023-12-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_groupsubstation_group_boss_and_more'),
        ('staff', '0014_alter_customuser_main_place_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='substation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.groupsubstation', verbose_name='Группа подстанций'),
        ),
    ]
