# Generated by Django 4.2.7 on 2023-12-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_groupsubstation_group_boss_and_more'),
        ('staff', '0015_customuser_substation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_place_work',
            field=models.ForeignKey(blank=True, help_text='Указывается только для персонала, закрепленного за ПС по штатному расписания (необязательно для заполнения).', null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.substation', verbose_name='Основное место работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Электромонтер по обслуживанию', 'Электромонтер по обслуживанию'), ('Дежурный инженер', 'Дежурный инженер'), ('Дежурный инженер 2 кат.', 'Дежурный инженер 2 кат.'), ('Дежурный инженер 1 кат.', 'Дежурный инженер 1 кат.'), ('Диспетчер', 'Диспетчер'), ('Ведущий инженер', 'Ведущий инженер'), ('Ведущий инженер по ОП', 'Ведущий инженер по ОП'), ('Начальник', 'Начальник'), ('АТП', 'АТП')], default='', max_length=120, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='substation_group',
            field=models.ForeignKey(blank=True, help_text='Указывается в какой группе ПС/ЦУС работает персонал.', null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.groupsubstation', verbose_name='Группа подстанций'),
        ),
    ]
