# Generated by Django 5.0.1 on 2024-01-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_customuser_position'),
        ('substation', '0008_alter_groupsubstation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_opj',
            field=models.ManyToManyField(blank=True, default=None, related_name='admin_opj', to='substation.substation', verbose_name='Просмотр служебной информации оперативного журнала'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='substation_group',
            field=models.ForeignKey(blank=True, help_text='Указывается в какой группе ПС, ЦУС, ПМЭС, МЭС работает персонал.', null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.groupsubstation', verbose_name='Группа подстанций'),
        ),
    ]
