# Generated by Django 5.0.1 on 2024-01-30 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0006_alter_autocompleteoption_disabling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='planned_completion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Планируемая дата ввода в работу'),
        ),
    ]
