# Generated by Django 5.0.1 on 2024-01-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0007_mainpageopjournal_planned_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocompleteoption',
            name='text',
            field=models.TextField(verbose_name='Текст автозаполнения'),
        ),
    ]
