# Generated by Django 5.0.1 on 2024-02-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0008_alter_autocompleteoption_text'),
        ('powerline', '0022_powerline_ending_alter_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteDisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='powerline.powerline', verbose_name='ВЛ')),
            ],
        ),
    ]
