# Generated by Django 5.0.1 on 2024-02-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0009_autocompletedisp'),
        ('powerline', '0033_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatchers', models.ManyToManyField(blank=True, to='powerline.thirdpartydispatchers')),
                ('powerline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='powerline.powerline')),
            ],
            options={
                'verbose_name': 'Быстрая запись дисп.',
                'verbose_name_plural': 'Быстрые записи дисп.',
            },
        ),
        migrations.DeleteModel(
            name='AutocompleteDisp',
        ),
    ]
