# Generated by Django 5.0.1 on 2024-02-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0011_alter_quickrecording_powerline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickRecording',
        ),
    ]
