# Generated by Django 5.0.1 on 2024-02-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0013_disprecordmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disprecordmodel',
            name='dispatchers',
        ),
    ]
