# Generated by Django 5.0.1 on 2024-02-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0014_remove_disprecordmodel_dispatchers'),
        ('powerline', '0033_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='disprecordmodel',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='powerline.thirdpartydispatchers', verbose_name='Диспетчеры'),
        ),
    ]
