# Generated by Django 5.0.1 on 2024-02-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0017_remove_disprecordmodel_dispatcherы_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispRecordModel',
        ),
    ]
