# Generated by Django 5.0.1 on 2024-02-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0019_disprecordmodel'),
        ('powerline', '0033_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименованеи ВЛ')),
                ('disp_manage', models.CharField(max_length=100, verbose_name='Диспетчерский центр')),
                ('dispatchers', models.CharField(max_length=100, verbose_name='Диспетчер')),
                ('induced_voltage', models.CharField(max_length=100, verbose_name='Наведенное напряжение')),
                ('substation', models.CharField(max_length=100, verbose_name='Подстанции')),
                ('CUS_dispatcher', models.CharField(max_length=100, verbose_name='Экспл.ведение')),
            ],
        ),
        migrations.AlterField(
            model_name='disprecordmodel',
            name='powerline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='powerline.powerline', verbose_name='Запись для ВЛ'),
        ),
    ]
