# Generated by Django 5.0.1 on 2024-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0028_selecteddata_cus_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecteddata',
            name='disp_manage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Диспетчерский центр'),
        ),
        migrations.AlterField(
            model_name='selecteddata',
            name='dispatchers',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Диспетчер'),
        ),
    ]
