# Generated by Django 5.0.1 on 2024-02-05 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0029_alter_selecteddata_disp_manage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddata',
            name='emergency_entry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время аварийной готовности'),
        ),
        migrations.AddField(
            model_name='selecteddata',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Работы закончить до: '),
        ),
    ]
