# Generated by Django 5.0.1 on 2024-02-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0031_autofilldispmodel_delete_disprecordmodel'),
        ('powerline', '0033_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofilldispmodel',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='powerline.powerline', verbose_name='Запись для ВЛ'),
            preserve_default=False,
        ),
    ]
