# Generated by Django 5.0.1 on 2024-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0032_alter_autofilldispmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='cus_dispatcher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Экспл.ведение'),
        ),
    ]
