# Generated by Django 5.0.1 on 2024-02-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0034_alter_autofilldispmodel_cus_dispatcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedData',
        ),
    ]
