# Generated by Django 5.0.1 on 2024-02-11 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0035_delete_selecteddata'),
        ('powerline', '0038_admittingstaff_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='admitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='powerline.admittingstaff', verbose_name='Допускающий'),
        ),
        migrations.AddField(
            model_name='autofilldispmodel',
            name='prm_tolerances',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Текст "Команда на допуск и ПРМиД на ВЛ"'),
        ),
        migrations.AlterField(
            model_name='autofilldispmodel',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='powerline.thirdpartydispatchers', verbose_name='Диспетчер'),
        ),
    ]
