# Generated by Django 5.0.1 on 2024-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0038_autofilldispmodel_admission_omly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='without_tripping',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Текст "Команда на работы без отключения"'),
        ),
    ]
