# Generated by Django 5.0.1 on 2024-02-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0040_autofilldispmodel_at_subst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autofilldispmodel',
            name='at_subst',
        ),
    ]
