# Generated by Django 5.0.1 on 2024-02-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0042_autofilldispmodel_anding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autofilldispmodel',
            name='anding',
        ),
    ]
