# Generated by Django 5.0.1 on 2024-02-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0043_remove_autofilldispmodel_anding'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='ending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.substation', verbose_name='На подстанции'),
        ),
    ]
