# Generated by Django 5.0.1 on 2024-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0045_autofilldispmodel_at_substation'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='and_work',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Текст "Работы на ВЛ закончены".'),
        ),
    ]
