# Generated by Django 5.0.1 on 2024-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0046_autofilldispmodel_and_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilldispmodel',
            name='submit_vl',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Текст "Передача ВЛ диспетчепу, в чьем она управлении".'),
        ),
    ]
