# Generated by Django 5.0.1 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0047_autofilldispmodel_submit_vl'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocompleteoption',
            name='label',
            field=models.CharField(blank=True, help_text='Этот текст будет отображаться в подсказках при вводе автозаписи', max_length=256, null=True, verbose_name='Краткое описание записи'),
        ),
    ]
