# Generated by Django 5.0.1 on 2024-02-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0048_autocompleteoption_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocompleteoption',
            name='label',
        ),
    ]
