# Generated by Django 5.0.1 on 2024-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0049_remove_autocompleteoption_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocompleteoption',
            name='label',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Сокращение, видимое при автовводе текста'),
        ),
    ]
