# Generated by Django 5.0.3 on 2024-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0050_autocompleteoption_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocompleteoption',
            name='disabling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Выводе в ремонт/отключении'),
        ),
        migrations.AlterField(
            model_name='autocompleteoption',
            name='enabling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Включении оборудования'),
        ),
        migrations.AlterField(
            model_name='autocompleteoption',
            name='getting_started',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Окончании работ'),
        ),
        migrations.AlterField(
            model_name='autocompleteoption',
            name='out_of_work',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Допуск к работам'),
        ),
    ]
