# Generated by Django 5.0.1 on 2024-01-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Диспетчерское наименование ВЛ', max_length=64, unique=True, verbose_name='Наименование ЛЭП')),
                ('voltage', models.CharField(choices=[('220', '220'), ('500', '500')], help_text='Класс напряжения', max_length=3, verbose_name='Напряжение ВЛ')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
                ('Induced_voltage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие наведенного напряжения на ВЛ')),
                ('ending_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_1', to='substation.substation', verbose_name='Заходит на ПС 1')),
                ('ending_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_2', to='substation.substation', verbose_name='Заходит на ПС 2')),
                ('ending_3', models.ForeignKey(blank=True, help_text='Указывается только если на ВЛ есть отпайка', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_3', to='substation.substation', verbose_name='Заходит на ПС 3')),
            ],
            options={
                'verbose_name': 'Линия электропередач',
                'verbose_name_plural': 'Линии электропередач',
            },
        ),
    ]
