# Generated by Django 5.0.1 on 2024-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0002_admittingstaff_manufacturerstaff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admittingstaff',
            options={'verbose_name': 'Допускающий', 'verbose_name_plural': 'Допускающий персонал'},
        ),
        migrations.AlterModelOptions(
            name='manufacturerstaff',
            options={'verbose_name': 'Производитель работ', 'verbose_name_plural': 'Производители работ'},
        ),
        migrations.AddField(
            model_name='admittingstaff',
            name='oganization',
            field=models.CharField(blank=True, choices=[('Самарское ПМЭС', 'Самарское ПМЭС'), ('Оренбургское ПМЭС', 'Оренбургское ПМЭС'), ('Средне-Волжское ПМЭС', 'Средне-Волжское ПМЭС')], help_text='Класс напряжения', max_length=20, null=True, verbose_name='Выберете предприятие'),
        ),
    ]
