# Generated by Django 5.0.1 on 2024-01-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0001_initial'),
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Фамилия И.О.')),
                ('position', models.CharField(help_text='Указать должность, как она будет отображаться в оперативном журнале', max_length=64, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Фамилия И.О.')),
                ('position', models.CharField(help_text='Указать должность, как она будет отображаться в оперативном журнале', max_length=64, verbose_name='Должность')),
                ('oganization', models.CharField(max_length=64, unique=True, verbose_name='Организация')),
            ],
        ),
        migrations.AlterField(
            model_name='powerline',
            name='Induced_voltage',
            field=models.BooleanField(default=False, verbose_name='Наличие наведенного напряжения на ВЛ'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_1',
            field=models.ForeignKey(limit_choices_to={'dispatch_point': False}, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_1', to='substation.substation', verbose_name='Заходит на ПС 1'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_2',
            field=models.ForeignKey(limit_choices_to={'dispatch_point': False}, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_2', to='substation.substation', verbose_name='Заходит на ПС 2'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_3',
            field=models.ForeignKey(blank=True, help_text='Указывается только если на ВЛ есть отпайка', limit_choices_to={'dispatch_point': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_3', to='substation.substation', verbose_name='Заходит на ПС 3'),
        ),
    ]
