# Generated by Django 5.0.1 on 2024-01-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0003_alter_admittingstaff_options_and_more'),
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerline',
            name='ending_3',
            field=models.ForeignKey(blank=True, help_text='Указывается только если на ВЛ есть вторая отпайка', limit_choices_to={'dispatch_point': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_4', to='substation.substation', verbose_name='Заходит на ПС 4'),
        ),
    ]
