# Generated by Django 5.0.1 on 2024-01-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0005_powerline_ending_4_alter_powerline_ending_3'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerline',
            name='for_CUS_dispatcher',
            field=models.ForeignKey(blank=True, help_text='Какому диспетчеру интересна эта ВЛ', limit_choices_to={'dispatch_point': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_CUS', to='substation.substation', verbose_name='Интересна диспетчеру'),
        ),
    ]
