# Generated by Django 5.0.1 on 2024-01-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0007_remove_powerline_for_cus_dispatcher_and_more'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerline',
            name='for_CUS_dispatcher',
            field=models.ManyToManyField(blank=True, help_text='Какому диспетчеру интересна эта ВЛ', limit_choices_to={'dispatch_point': True}, to='substation.substation', verbose_name='Интересна диспетчеру'),
        ),
    ]
