# Generated by Django 5.0.1 on 2024-02-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0010_alter_powerline_ending_1_alter_powerline_ending_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerline',
            name='third_party_object',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта', max_length=64, null=True, verbose_name='Сторонний объект'),
        ),
    ]
