# Generated by Django 5.0.1 on 2024-02-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0012_rename_third_party_object_powerline_third_party_object_1_and_more'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerline',
            name='third_party_object_3',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле)', max_length=64, null=True, verbose_name='Сторонний объект 3'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_1',
            field=models.ForeignKey(help_text='Обязательное поле', limit_choices_to={'dispatch_point': False}, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_1', to='substation.substation', verbose_name='Заходит на ПС 1'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_2',
            field=models.ForeignKey(blank=True, help_text='Если ВЛ с обратной стороны подключена к объектам третьих лиц, то это указывается в поле "Сторонний объект 1" (необязательное поле)', limit_choices_to={'dispatch_point': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_2', to='substation.substation', verbose_name='Заходит на ПС 2'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_3',
            field=models.ForeignKey(blank=True, help_text='Указывается только если на ВЛ есть одна отпайка (необязательное поле)', limit_choices_to={'dispatch_point': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_3', to='substation.substation', verbose_name='Заходит на ПС 3'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='ending_4',
            field=models.ForeignKey(blank=True, help_text='Указывается только если на ВЛ есть вторая отпайка (необязательное поле)', limit_choices_to={'dispatch_point': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='powerline_ending_4', to='substation.substation', verbose_name='Заходит на ПС 4'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='third_party_object_1',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле)', max_length=64, null=True, verbose_name='Сторонний объект 1'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='third_party_object_2',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле)', max_length=64, null=True, verbose_name='Сторонний объект 2'),
        ),
    ]
