# Generated by Django 5.0.1 on 2024-02-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0013_powerline_third_party_object_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, unique=True, verbose_name='Полное наименование организации диспетчерского центра')),
                ('abbreviated_name', models.CharField(max_length=64, unique=True, verbose_name='Сокращенное наименование')),
                ('abbreviated_name_rp', models.CharField(help_text='Сокращенное наименование ДЦ в родительском падеже', max_length=64, unique=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Диспетчерский центр',
                'verbose_name_plural': 'Диспетчерские центры',
            },
        ),
        migrations.AlterField(
            model_name='admittingstaff',
            name='oganization',
            field=models.CharField(blank=True, choices=[('Самарское ПМЭС', 'Самарское ПМЭС'), ('Оренбургское ПМЭС', 'Оренбургское ПМЭС'), ('Средне-Волжское ПМЭС', 'Средне-Волжское ПМЭС')], help_text='Укажите организацию работы стороннего диспетчера', max_length=20, null=True, verbose_name='Выберете предприятие'),
        ),
    ]
