# Generated by Django 5.0.1 on 2024-02-01 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0014_dispatchcompanies_alter_admittingstaff_oganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyDispatchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_name', models.CharField(max_length=64, verbose_name='Фамилия И.О. диспетчера стороннего ДЦ')),
                ('dispatch_сenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_сenter', to='powerline.dispatchcompanies', verbose_name='Диспетчерский центр')),
            ],
            options={
                'verbose_name': 'Сторонний диспетчер',
                'verbose_name_plural': 'Сторонние диспетчера',
            },
        ),
    ]
