# Generated by Django 5.0.1 on 2024-02-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0015_thirdpartydispatchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartydispatchers',
            name='disp_post',
            field=models.CharField(max_length=64, null=True, verbose_name='Должность персонала стороннего ДЦ'),
        ),
        migrations.AlterField(
            model_name='thirdpartydispatchers',
            name='disp_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия И.О. персонала стороннего ДЦ'),
        ),
        migrations.AlterField(
            model_name='thirdpartydispatchers',
            name='dispatch_сenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_сenter', to='powerline.dispatchcompanies', verbose_name='Диспетчерский центр'),
        ),
    ]
