# Generated by Django 5.0.1 on 2024-02-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0018_powerline_disp_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchcompanies',
            name='disp3spetcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disp3spetcher', to='powerline.thirdpartydispatchers', verbose_name='Диспетчер'),
        ),
    ]
