# Generated by Django 5.0.1 on 2024-02-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0020_remove_dispatchcompanies_disp3spetcher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerline',
            name='ending_1',
        ),
        migrations.RemoveField(
            model_name='powerline',
            name='ending_2',
        ),
        migrations.RemoveField(
            model_name='powerline',
            name='ending_3',
        ),
        migrations.RemoveField(
            model_name='powerline',
            name='ending_4',
        ),
    ]
