# Generated by Django 5.0.1 on 2024-02-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0021_remove_powerline_ending_1_remove_powerline_ending_2_and_more'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerline',
            name='ending',
            field=models.ManyToManyField(blank=True, help_text='Обязательное поле', limit_choices_to={'dispatch_point': False}, related_name='powerline_endings', to='substation.substation', verbose_name='ВЛ заходит на следующие ПС'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='for_CUS_dispatcher',
            field=models.ManyToManyField(blank=True, help_text='Какому диспетчеру интересна эта ВЛ', limit_choices_to={'dispatch_point': True}, related_name='dispatcher_interests', to='substation.substation', verbose_name='Интересна диспетчеру'),
        ),
    ]
