# Generated by Django 5.0.1 on 2024-02-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0023_remove_powerline_induced_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerline',
            name='induced_voltage',
            field=models.BooleanField(default=False, verbose_name='Наличие наведенного напряжения на ВЛ'),
        ),
    ]
