# Generated by Django 5.0.1 on 2024-02-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0024_powerline_induced_voltage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchcompanies',
            name='disp3spetcher',
        ),
    ]
