# Generated by Django 5.0.1 on 2024-02-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0025_remove_dispatchcompanies_disp3spetcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartydispatchers',
            name='disp_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='powerline.dispatchcompanies', verbose_name='Диспетчерский центр'),
        ),
    ]
