# Generated by Django 5.0.1 on 2024-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0028_remove_thirdpartydispatchers_disp_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartydispatchers',
            name='disp_center',
            field=models.ManyToManyField(blank=True, default=None, related_name='disp_center', to='powerline.dispatchcompanies', verbose_name='Диспетчерский центр'),
        ),
    ]
