# Generated by Django 5.0.1 on 2024-02-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0033_powerline_for_cus_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerline',
            name='third_party_object_1',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле). Объекты генерации указывать в родительском падеже.', max_length=64, null=True, verbose_name='Сторонний объект 1'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='third_party_object_2',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле). Объекты генерации указывать в родительском падеже.', max_length=64, null=True, verbose_name='Сторонний объект 2'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='third_party_object_3',
            field=models.CharField(blank=True, help_text='Если ВЛ подключена к объектам третьих лиц, укажите ДН этого объекта (необязательное поле). Объекты генерации указывать в родительском падеже.', max_length=64, null=True, verbose_name='Сторонний объект 3'),
        ),
    ]
