# Generated by Django 5.0.1 on 2024-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0035_delete_manufacturerstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartydispatchers',
            name='disp_name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Фамилия И.О.'),
        ),
    ]
