# Generated by Django 5.0.1 on 2024-02-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0036_alter_thirdpartydispatchers_disp_name'),
        ('substation', '0002_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittingstaff',
            name='oganization',
        ),
        migrations.AddField(
            model_name='admittingstaff',
            name='for_CUS_dispatcher',
            field=models.ManyToManyField(blank=True, help_text='Какому диспетчеру будет доступен этот допускающий для заполнения автоформы', limit_choices_to={'dispatch_point': True}, related_name='dispatcher_admit', to='substation.substation', verbose_name='Для диспетчера ЦУС'),
        ),
        migrations.AlterField(
            model_name='admittingstaff',
            name='position',
            field=models.CharField(blank=True, help_text='Должность полностью, включая пренадлежность к организации', max_length=64, null=True, verbose_name='Должность'),
        ),
    ]
