# Generated by Django 5.0.1 on 2024-02-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline', '0037_remove_admittingstaff_oganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittingstaff',
            name='organization',
            field=models.CharField(blank=True, help_text='Организация, где работает допускающий. В родительном падеже (нет чего?)', max_length=64, null=True, verbose_name='От организации'),
        ),
        migrations.AlterField(
            model_name='admittingstaff',
            name='name',
            field=models.CharField(help_text='Фамилия И.О. В дательном падеже (кому?)', max_length=64, unique=True, verbose_name='Фамилия И.О.'),
        ),
        migrations.AlterField(
            model_name='admittingstaff',
            name='position',
            field=models.CharField(blank=True, help_text='Должность допускающего. В дательном падеже (кому?)', max_length=64, null=True, verbose_name='Должность'),
        ),
    ]
