# Generated by Django 5.0.1 on 2024-01-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указываются группы ПС, ЦУС, предприятия, а также МЭС', max_length=64, unique=True, verbose_name='Название группы ПС, ЦУС, ПМЭС или МЭС')),
                ('name_rp', models.CharField(blank=True, help_text='Название группы этого же структурного подразделения в родительском падеже', max_length=64, null=True, verbose_name='Название СП в родительском падеже')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Группа подстанций',
                'verbose_name_plural': 'Группы подстанций',
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указываются только подстанции предприятия', max_length=64, unique=True, verbose_name='Название ПС')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
                ('dispatch_point', models.BooleanField(default=False, verbose_name='Является диспетчерским пунктом')),
                ('dispatcher_for', models.ManyToManyField(blank=True, help_text='Выберите объекты для диспетчеризации этого ДП', to='substation.substation', verbose_name='Диспетчер для:')),
                ('group_substation', models.ForeignKey(blank=True, help_text='Прописываются только существующие группы ПС', null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.groupsubstation', verbose_name='Группа подстанций')),
            ],
            options={
                'verbose_name': 'Подстанция',
                'verbose_name_plural': 'Подстанции',
            },
        ),
    ]
