# Generated by Django 5.0.1 on 2024-01-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='dispatcher_for',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты для диспетчеризации этого ДП', to='substation.substation', verbose_name='Диспетчер для ПС:'),
        ),
    ]
