# Generated by Django 5.0.1 on 2024-01-26 19:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096, verbose_name='Текст автозаполнения')),
                ('out_of_work', models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись добавляет отклонение на объекте')),
                ('getting_started', models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись об исключении из отклонений на объекте')),
                ('substation', models.ManyToManyField(default=None, related_name='for_substation', to='substation.substation', verbose_name='Для подстанции')),
            ],
            options={
                'verbose_name': 'Автозаполнение формы',
                'verbose_name_plural': 'Автозаполнений форм',
            },
        ),
        migrations.CreateModel(
            name='MainPageOPJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('real_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время создания записи пользователем')),
                ('pub_date', models.DateTimeField(verbose_name='Время выполнения действия')),
                ('entry_is_valid', models.BooleanField(default=True, verbose_name='Запись верна')),
                ('special_regime_introduced', models.BooleanField(default=False, verbose_name='Ввод особого режима (ОРР, РПГ, РВР)')),
                ('emergency_event', models.BooleanField(default=False, verbose_name='Аварийное событие')),
                ('short_circuit', models.BooleanField(default=False, verbose_name='КЗ в сети 6-35 кВ')),
                ('user_signature', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Подпись пользователя')),
                ('closing_entry', models.ManyToManyField(blank=True, default=None, help_text='Выберете связанную запись, исключающую текущую запись из отклонений', to='op_journal.mainpageopjournal', verbose_name='Закрыта записью')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substation', to='substation.substation', verbose_name='Подстанция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Запись сделал')),
            ],
            options={
                'verbose_name': 'Запись опер. журнала',
                'verbose_name_plural': 'Записи опер. журналов',
            },
        ),
        migrations.CreateModel(
            name='FileModelOPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='OPJ/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('main_page_op_journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='op_journal.mainpageopjournal')),
            ],
            options={
                'verbose_name': 'Доп. файл',
                'verbose_name_plural': 'Дополнительные материалы',
            },
        ),
        migrations.CreateModel(
            name='СommentOPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('real_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания комментария')),
                ('user_signature', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Подпись пользователя')),
                ('user', models.ForeignKey(default='Пользователь удален', on_delete=django.db.models.deletion.PROTECT, related_name='commentator', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий сделал')),
            ],
            options={
                'verbose_name': 'Комментарий к ОЖ',
                'verbose_name_plural': 'Комментарии к ОЖ',
            },
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='op_journal.сommentopj', verbose_name='Комментарий'),
        ),
    ]
