# Generated by Django 4.2.7 on 2023-11-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substation', '0003_alter_substation_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageOPJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('real_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время создания записи пользователем')),
                ('pub_date', models.DateTimeField(verbose_name='Время выполнения действия')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substation', to='substation.substation', verbose_name='Подстанция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Запись сделал')),
            ],
        ),
    ]
