# Generated by Django 4.2.7 on 2023-11-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageopjournal',
            options={'verbose_name': 'Запись опер. журнала', 'verbose_name_plural': 'Запись опер. журналов'},
        ),
    ]
