# Generated by Django 5.0.1 on 2024-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='permission_to_work',
            field=models.BooleanField(default=True, verbose_name='Запись о допуске к выполнению работ'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='withdrawal_for_repair',
            field=models.BooleanField(default=True, verbose_name='Запись о выводе оборудования из работы'),
        ),
    ]
