# Generated by Django 4.2.7 on 2023-11-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0002_alter_mainpageopjournal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageopjournal',
            options={'verbose_name': 'Запись опер. журнала', 'verbose_name_plural': 'Записи опер. журналов'},
        ),
    ]
