# Generated by Django 4.2.7 on 2023-11-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0003_alter_mainpageopjournal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
