# Generated by Django 5.0.1 on 2024-01-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0004_alter_mainpageopjournal_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocompleteoption',
            name='disabling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись о выводе к ремонт/отключении'),
        ),
        migrations.AddField(
            model_name='autocompleteoption',
            name='enabling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись о включении оборудования'),
        ),
        migrations.AlterField(
            model_name='autocompleteoption',
            name='getting_started',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись об окончании работ'),
        ),
        migrations.AlterField(
            model_name='autocompleteoption',
            name='out_of_work',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись о допуске к работам'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='permission_to_work',
            field=models.BooleanField(default=False, verbose_name='Запись о допуске к выполнению работ'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='withdrawal_for_repair',
            field=models.BooleanField(default=False, verbose_name='Запись о выводе оборудования из работы'),
        ),
    ]
