# Generated by Django 4.2.7 on 2023-11-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0004_suggestedtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestedtext',
            options={'verbose_name': 'Автозаполнение формы', 'verbose_name_plural': 'Автозаполнение форм'},
        ),
    ]
