# Generated by Django 4.2.7 on 2023-11-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0005_alter_suggestedtext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Автозаполнение формы',
                'verbose_name_plural': 'Автозаполнение форм',
            },
        ),
        migrations.DeleteModel(
            name='SuggestedText',
        ),
    ]
