# Generated by Django 5.0.1 on 2024-01-27 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0005_autocompleteoption_disabling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocompleteoption',
            name='disabling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись о выводе в ремонт/отключении'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выполнения действия'),
        ),
    ]
