# Generated by Django 4.2.7 on 2023-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0007_delete_autocompleteoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Автозаполнение формы',
                'verbose_name_plural': 'Автозаполнение форм',
            },
        ),
    ]
