# Generated by Django 4.2.7 on 2023-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0008_autocompleteoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocompleteoption',
            name='text',
            field=models.TextField(),
        ),
    ]
