# Generated by Django 4.2.7 on 2023-11-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0009_alter_autocompleteoption_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutocompleteOption',
        ),
    ]
