# Generated by Django 4.2.7 on 2023-11-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0011_suggestedtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedText',
        ),
    ]
