# Generated by Django 4.2.7 on 2023-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0015_mainpageopjournal_entry_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='emergency_event',
            field=models.BooleanField(default=False, verbose_name='Аварийное событие'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='short_circuit',
            field=models.BooleanField(default=False, verbose_name='КЗ в сети 6-35 кВ'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='special_regime_introduced',
            field=models.BooleanField(default=False, verbose_name='Ввод особого режима (ОРР, РПГ, РВР)'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='entry_is_valid',
            field=models.BooleanField(default=True, verbose_name='Запись верна'),
        ),
    ]
