# Generated by Django 4.2.7 on 2023-11-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0003_alter_substation_slug'),
        ('op_journal', '0016_mainpageopjournal_emergency_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocompleteoption',
            name='substation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='for_substation', to='substation.substation', verbose_name='Для подстанции'),
        ),
    ]
