# Generated by Django 4.2.7 on 2023-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0003_alter_substation_slug'),
        ('op_journal', '0017_autocompleteoption_substation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocompleteoption',
            name='substation',
        ),
        migrations.AddField(
            model_name='autocompleteoption',
            name='substation',
            field=models.ManyToManyField(default=None, related_name='for_substation', to='substation.substation', verbose_name='Для подстанции'),
        ),
    ]
