# Generated by Django 4.2.7 on 2023-11-25 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('op_journal', '0018_remove_autocompleteoption_substation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='СommentOPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('real_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания комментария')),
                ('user', models.ForeignKey(default='Пользователь удален', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='commentator', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий сделал')),
            ],
            options={
                'verbose_name': 'Комментарий к ОЖ',
                'verbose_name_plural': 'Комментарии к ОЖ',
            },
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='op_journal.сommentopj', verbose_name='Комментарий'),
        ),
    ]
