# Generated by Django 4.2.7 on 2023-11-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0019_alter_mainpageopjournal_comment_сommentopj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='op_journal.сommentopj', verbose_name='Комментарий'),
        ),
    ]
