# Generated by Django 4.2.7 on 2023-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0020_alter_mainpageopjournal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Дополнительные файлы'),
        ),
    ]
