# Generated by Django 4.2.7 on 2023-12-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0021_mainpageopjournal_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageopjournal',
            name='file',
        ),
    ]
