# Generated by Django 4.2.7 on 2023-12-09 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0022_remove_mainpageopjournal_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModelOPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='OPJ/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
            ],
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='files',
            field=models.ManyToManyField(blank=True, to='op_journal.filemodelopj', verbose_name='Дополнительные материалы'),
        ),
    ]
