# Generated by Django 4.2.7 on 2023-12-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0023_filemodelopj_mainpageopjournal_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageopjournal',
            name='files',
        ),
        migrations.DeleteModel(
            name='FileModelOPJ',
        ),
    ]
