# Generated by Django 4.2.7 on 2023-12-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0025_filemodelopj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodelopj',
            options={'verbose_name': 'Доп. файл', 'verbose_name_plural': 'Дополнительные материалы'},
        ),
    ]
