# Generated by Django 4.2.7 on 2023-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0026_alter_filemodelopj_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='user_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность пользователя'),
        ),
    ]
