# Generated by Django 4.2.7 on 2023-12-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0027_mainpageopjournal_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='сommentopj',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='сommentopj',
            name='user_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность пользователя'),
        ),
    ]
