# Generated by Django 4.2.7 on 2023-12-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0028_сommentopj_user_name_сommentopj_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='user_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
