# Generated by Django 4.2.7 on 2023-12-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0030_remove_mainpageopjournal_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сommentopj',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='сommentopj',
            name='user_position',
        ),
        migrations.AddField(
            model_name='сommentopj',
            name='user_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись пользователя'),
        ),
    ]
