# Generated by Django 5.0.1 on 2024-01-07 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0031_remove_сommentopj_user_name_and_more'),
        ('substation', '0008_alter_groupsubstation_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodelopj',
            name='main_page_op_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='op_journal.mainpageopjournal'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='op_journal.сommentopj', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substation', to='substation.substation', verbose_name='Подстанция'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Запись сделал'),
        ),
        migrations.AlterField(
            model_name='сommentopj',
            name='user',
            field=models.ForeignKey(default='Пользователь удален', on_delete=django.db.models.deletion.PROTECT, related_name='commentator', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий сделал'),
        ),
    ]
