# Generated by Django 5.0.1 on 2024-01-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0032_alter_filemodelopj_main_page_op_journal_and_more'),
        ('substation', '0008_alter_groupsubstation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_start_date', models.DateTimeField(verbose_name='Время выполнения действия')),
                ('repair_over_date', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения действия')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('user_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись пользователя')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_deviation', to='substation.substation', verbose_name='Подстанция')),
            ],
        ),
    ]
