# Generated by Django 5.0.1 on 2024-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0033_deviationscheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviationscheme',
            options={'verbose_name': 'Учет отклонений схемы ПС', 'verbose_name_plural': 'Учет отклонений схем ПС'},
        ),
    ]
