# Generated by Django 5.0.1 on 2024-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0035_deviationscheme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageopjournal',
            name='important_event_date_over',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ввод в работу/окончание работ, допущенной бригады'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='important_event_date_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Вывод в ремонт/допуск бригады'),
        ),
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='user_signature',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Подпись пользователя'),
        ),
        migrations.AlterField(
            model_name='сommentopj',
            name='user_signature',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Подпись пользователя'),
        ),
        migrations.DeleteModel(
            name='DeviationScheme',
        ),
    ]
