# Generated by Django 5.0.1 on 2024-01-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0036_mainpageopjournal_important_event_date_over_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocompleteoption',
            options={'verbose_name': 'Автозаполнение формы', 'verbose_name_plural': 'Автозаполнений форм'},
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='impl_text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание записи ввода в работу'),
        ),
        migrations.AddField(
            model_name='mainpageopjournal',
            name='impl_user_signature',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True, verbose_name='Закрыл запись'),
        ),
    ]
