# Generated by Django 5.0.1 on 2024-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0037_alter_autocompleteoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='impl_user_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Отклонение закрыл'),
        ),
    ]
