# Generated by Django 5.0.1 on 2024-01-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0038_alter_mainpageopjournal_impl_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageopjournal',
            name='impl_text',
        ),
        migrations.RemoveField(
            model_name='mainpageopjournal',
            name='impl_user_signature',
        ),
    ]
