# Generated by Django 5.0.1 on 2024-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_journal', '0040_mainpageopjournal_closing_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageopjournal',
            name='closing_entry',
            field=models.ManyToManyField(blank=True, default=None, help_text='Выберете связанную запись, исключающую текущую запись из отклонений', to='op_journal.mainpageopjournal', verbose_name='Закрыта записью'),
        ),
    ]
