# Generated by Django 4.2.7 on 2023-11-07 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название группы ПС')),
                ('group_boss', models.CharField(blank=True, max_length=64, null=True, verbose_name='Начальник гр. ПС')),
                ('group_engineer', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ведущий инженер гр. ПС')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Группа подстанций',
                'verbose_name_plural': 'Группы подстанций',
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название ПС')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('group_substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='substation.groupsubstation', verbose_name='Группа подстанций')),
                ('substation_boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Начальник ПС')),
            ],
            options={
                'verbose_name': 'Подстанция',
                'verbose_name_plural': 'Подстанции',
            },
        ),
    ]
