# Generated by Django 4.2.7 on 2023-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Слаг'),
        ),
    ]
