# Generated by Django 4.2.7 on 2023-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0002_substation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
