# Generated by Django 4.2.7 on 2023-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0003_alter_substation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubstation',
            name='group_boss',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='groupsubstation',
            name='group_engineer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ведущий инженер'),
        ),
    ]
