# Generated by Django 4.2.7 on 2023-12-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_alter_groupsubstation_group_boss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubstation',
            name='group_boss',
        ),
    ]
