# Generated by Django 4.2.7 on 2023-12-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0007_groupsubstation_name_rp_alter_groupsubstation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubstation',
            name='name',
            field=models.CharField(help_text='Указываются группы ПС, ЦУС, предприятия, а также МЭС', max_length=64, unique=True, verbose_name='Название группы ПС, ЦУС, ПМЭС или МЭС'),
        ),
        migrations.AlterField(
            model_name='groupsubstation',
            name='name_rp',
            field=models.CharField(blank=True, help_text='Название группы этого же структурного подразделения в родительском падеже', max_length=64, null=True, verbose_name='Название СП в родительском падеже'),
        ),
    ]
