# Generated by Django 5.0.1 on 2024-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0008_alter_groupsubstation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='dispatching',
            field=models.ManyToManyField(blank=True, null=True, to='substation.substation', verbose_name='Связанные записи'),
        ),
    ]
