# Generated by Django 5.0.1 on 2024-01-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0010_alter_substation_dispatching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='dispatching',
        ),
    ]
