# Generated by Django 5.0.1 on 2024-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0011_remove_substation_dispatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='dispatch_point',
            field=models.BooleanField(default=False, verbose_name='Является диспетчерским пунктом:'),
        ),
        migrations.AddField(
            model_name='substation',
            name='dispatcher_for',
            field=models.ManyToManyField(blank=True, help_text='Выберите подстанции, для которых этот экземпляр является диспетчером', related_name='dispatchers', to='substation.substation', verbose_name='Диспетчер для'),
        ),
    ]
