# Generated by Django 5.0.1 on 2024-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0012_substation_dispatch_point_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='dispatcher_for',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты для диспетчеризации этого ДП', to='substation.substation', verbose_name='Диспетчер для:'),
        ),
    ]
