# Generated by Django 5.0.1 on 2024-01-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0013_alter_substation_dispatcher_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='dispatch_point',
            field=models.BooleanField(default=False, verbose_name='Является диспетчерским пунктом'),
        ),
    ]
