# Generated by Django 5.0.1 on 2024-01-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0014_alter_substation_dispatch_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='dispatch_points',
            field=models.BooleanField(default=False, verbose_name='Является диспетчерским пунктом'),
        ),
    ]
