# Generated by Django 5.0.1 on 2024-01-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0015_substation_dispatch_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='dispatch_points',
        ),
    ]
